language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
install: "pip install ."
script: "python setup.py nosetests"
sudo: false

env:
  global:
    - CI=true

matrix:
  include:
    env:
      OPENSSL=1.0.1
