language: python
install: "pip install ."
script: "python setup.py nosetests"
sudo: false

env:
  global:
    - CI=true

matrix:
  include:
  # Also run the tests against cryptography master.
  - python: "2.6"
    env:
      OPENSSL=1.0.1
      CI=true
  - python: "2.7"
    env:
      OPENSSL=1.0.1
      CI=true
  - python: "3.4"
    env:
      OPENSSL=1.0.1
      CI=true
  - python: "3.5"
    env:
      OPENSSL=1.0.1
      CI=true
  - python: "pypy"
    env:
      OPENSSL=1.0.1
      CI=true
